### ISSUE TITLE
Marking normal maps as such on import

### ISSUE THREAD

**Issue by peteradvr** [ousttrue/UniGLTF#1]
Unity complains that textures used as normal maps aren't marked as such when you drag/drop a GLTF and its corresponding textures into a Unity project.  

Here is how I automated marking them so as to avoid getting that error dialog:
in
static TextureItem _ImportTexture(glTF gltf, int index)
in the 
else if (gltf.baseDir.StartsWith("Assets/"))
code path
save off the asset path into the TextureItem
then in 
TextureItem.cs 
I added a method like this:
```
        public void MarkTextureAssetAsNormalMap()
        {
            if (string.IsNullOrEmpty(assetPath))
                return;

            TextureImporter textureImporter = AssetImporter.GetAtPath(assetPath) as TextureImporter;
            if (null == textureImporter) {
                return;
            }
            textureImporter.textureType = TextureImporterType.NormalMap;
            textureImporter.SaveAndReimport();
        }
```
then in
public static CreateMaterialFunc CreateMaterialFuncFromShader(Shader shader)
inside the
if (x.normalTexture.index != -1)
code block, I added a call to 
texture.MarkTextureAssetAsNormalMap();

Thanks for the work you have done here!  Your GLTF importer is the cleanest I've seen so far.

**Comment by ousttrue** [comment]
I appreciate your advice.
I will do it from now.

**Comment by ousttrue** [comment]
Implemented

https://github.com/ousttrue/UniGLTF/commit/c5878a7d6263c12d9b2ab66ac689bfcae827ad0f#diff-14c36fee31024bc00d515eeafeddedd1
