### ISSUE TITLE
gltfExporter may have to add morphTarget to all primitives

### ISSUE THREAD

**Issue by rdrgn** [ousttrue/UniGLTF#18]
UniGLTF（UniVRM）で出力したVRMモデルを[three.js](https://github.com/mrdoob/three.js/)でモーフィングする際、meshにprimitiveが複数あるような場合に、その内の1つしかモーフしない症状に遭遇しました。

色々とモーフに関連するコードを当たった結果、UniGLTFの以下の部分で`morphTarget`を`gltfMesh.primitives[0]`にしか追加していないことによるものではないかと考え、下記のように書き変えると（おそらく）正常にモーフできるようになりました。

three.jsのglTFローダ側で対処することも考えられましたが、[glTFの仕様](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#morph-targets)を見るに`targets`を省略することは想定されてなさそうでしたので、こちらでissueを書きました。🙇 

> All primitives are required to list the same number of `targets` in the same order.

---

https://github.com/ousttrue/UniGLTF/blob/b6d373045472f774350363b48b381ebe95c63000/Core/Scripts/IO/gltfExporter.cs#L506-L512

![image](https://user-images.githubusercontent.com/9990535/44460714-2c3fc400-a649-11e8-89b4-164731add3a9.png)

```cs
for (int k = 0; k < gltfMesh.primitives.Count; ++k) {
    gltfMesh.primitives[k].targets.Add(morphTarget);
    gltfMesh.primitives[k].extras.targetNames.Add(mesh.GetBlendShapeName(j));
}
```

![image](https://user-images.githubusercontent.com/9990535/44460761-4c6f8300-a649-11e8-8dde-41589a57a880.png)

**Comment by ousttrue** [comment]
フィードバックありがとうございます。
修正取り入れさせていただきます。
