### ISSUE TITLE
Dirty frames are getting introduced in animation - animation looks messed up

### ISSUE THREAD

**Issue by chakitp** [ousttrue/UniGLTF#19]
Dirty frames are getting introduced in animation - animation looks messed up

Below is the gltf model which was tested on babylon js sandbox and loaded using UniGLTF plugin from Unity editor. Animations were rendered properly on babylon sandbox however dirty frames got introduced when played using UniGLTF plugin from Unity editor. (For Example: Play and observe frames form 0 to 2000 on Babylon sandbox and UniGLTF plugin on Unity editor)

Bablylon Sandbox:
[https://sandbox.babylonjs.com/](url)

GLTF Model:
[ge_gltf.zip](https://github.com/ousttrue/UniGLTF/files/2318001/ge_gltf.zip)

**Comment by ousttrue** [comment]
Thank you for your feedback.
I will investigate.

**Comment by chakitp** [comment]
@ousttrue  Your solution worked nicely for me. Thanks a lot. You Saved my day!
