### ISSUE TITLE
normal map export incorrect

### ISSUE THREAD

**Issue by iCyP** [ousttrue/UniGLTF#29]
https://github.com/dwango/UniVRM/issues/38　より、

https://github.com/ousttrue/UniGLTF/blob/60d9b4802a949fb82e776e960fb38803d2a98da7/Resources/Shaders/Dxt5Decoder.shader#L47
col.z は col.wの間違いでは？B(z)成分が常に1になり、alpha成分がimport時のrを読み込んだまま上書きされず半透明になる原因と思います。

また、参照がないみたいなので修正不要かもしれませんが、https://github.com/ousttrue/UniGLTF/blob/60d9b4802a949fb82e776e960fb38803d2a98da7/Core/Scripts/IO/TextureItem.cs#L235 　関数名typo？(DTXnm<>DXTnm)

**Comment by ousttrue** [comment]
フィードバックありがとうございます。
ご指摘の通り。修正します。

**Comment by ousttrue** [comment]
`DTXnm2RGBA`の方は多分無くなる
