### ISSUE TITLE
Sparse Accessorに対応していない

### ISSUE THREAD

**Issue by vyv03354** [ousttrue/UniGLTF#6]
現在UniGLTFはモーフ1つにつき、実際に変化があったかどうかにかかわらずすべての頂点のジオメトリ情報を出力しているので、モーフが増えるにつれてファイルサイズがものすごい勢いで増加していきます。このため顔部分だけ人力で[メッシュを分割する](https://ameblo.jp/b4u0621/entry-12376496973.html)などのバッドノウハウで対策が行われています。

glTF 2.0には[Sparse Accessor](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#sparse-accessors)という、差分の情報だけを記録する仕組みが標準で提供されているので、これを使ってファイルサイズを節約できないでしょうか。

現状ではインポートしたファイルにsparseが含まれていても無視してしまう(その結果モーフが効かないなどの現象が発生する可能性がある)ので、glTF 2.0仕様への準拠の観点からも問題があります。

**Comment by ousttrue** [comment]
ToDo https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SimpleSparseAccessor

**Comment by ousttrue** [comment]
ToDo: blendShape export

**Comment by ousttrue** [comment]
Fixed
