### ISSUE TITLE
Blend shapes broken when imported. 

### ISSUE THREAD

**Issue by tiancaipipi110** [ousttrue/UniGLTF#65]
Hello, just tried the sample scene, the blend shapes are broken somehow.

**Comment by tiancaipipi110** [comment]
![monkeybs](https://user-images.githubusercontent.com/35275506/51790354-1e471f80-2162-11e9-9101-0162a6f6e832.gif)

**Comment by ousttrue** [comment]
Please paste the import source gltf(glb) . Thank you.
